#first_name="raha"
#last_name="rahpeima"
#age=41
#city="shiraz"
#user_data=[first_name,age,last_name,age,city]
#user_data.append(70)
#user_data.insert(0,70)
#user_data.pop()
#user_data.pop(1)
#user_data.remove("rahpeima")
#print(user_data.count(41))
#print(user_data,len(user_data))

#print(user_data.index(41))
#ages=[23,45,28,71,19,35,69]
#ages.sort()
#ages.sort(reverse=True)
#print(ages)
#print(sorted(ages,reverse=True))
